<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="2" time="18.761">
 <testsuite name="demo calculator" timestamp="2020-04-23T23:17:31" hostname="localhost" time="18.761" errors="0" tests="2" skipped="0" disabled="0" failures="1">
  <testcase classname="demo calculator" name="addition testing" time="9.763" />
  <testcase classname="demo calculator" name="addition testing negative" time="8.994">
   <failure type="toEqual" message="Expected &apos;50&apos; to equal &apos;455&apos;."><![CDATA[Error: Failed expectation
    at UserContext.<anonymous> (C:\Users\srinivas.godari\Desktop\New Courses\ProtractorSessionApril2020\MYDemo1\tests\mytc.js:20:30)
    at C:\Users\srinivas.godari\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\srinivas.godari\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\srinivas.godari\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\srinivas.godari\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\srinivas.godari\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\srinivas.godari\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at C:\Users\srinivas.godari\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27
    at C:\Users\srinivas.godari\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>